import type { Audience, Company, Format, Level, Topic } from "./taxonomy";

export type Guide = {
  title: string;
  company: Company;
  topic: Topic;
  url: string;
  format: Format;
  year: number;
  pages?: number;
  level: Level;
  audience: Audience;
  description: string;
};

// every entry is published by the lab itself.
// no third-party explainers, no reuploaded pdfs.
export const GUIDES: Guide[] = [
  // ── Anthropic ──────────────────────────────────────────────
  {
    title: "The Complete Guide to Building Skills for Claude",
    company: "Anthropic",
    topic: "Skills & Tooling",
    url: "https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf",
    format: "PDF",
    year: 2025,
    pages: 33,
    level: "build",
    audience: "builder",
    description:
      "how to package instructions, scripts and resources into skills claude loads on demand. the patterns anthropic runs internally.",
  },
  {
    title: "Building Effective AI Agents",
    company: "Anthropic",
    topic: "Agents",
    url: "https://resources.anthropic.com/hubfs/Building%20Effective%20AI%20Agents-%20Architecture%20Patterns%20and%20Implementation%20Frameworks.pdf",
    format: "PDF",
    year: 2025,
    level: "build",
    audience: "builder",
    description:
      "architecture patterns for agentic systems. prompt chaining, routing, orchestration, with real production examples.",
  },
  {
    title: "Building Trusted AI in the Enterprise",
    company: "Anthropic",
    topic: "Enterprise & Adoption",
    url: "https://assets.anthropic.com/m/66daaa23018ab0fd/original/Anthropic-enterprise-ebook-digital.pdf",
    format: "PDF",
    year: 2025,
    level: "intro",
    audience: "founder",
    description: "the playbook for starting, scaling and governing claude across a company.",
  },
  {
    title: "Claude Code: Best Practices for Agentic Coding",
    company: "Anthropic",
    topic: "Skills & Tooling",
    url: "https://www.anthropic.com/engineering/claude-code-best-practices",
    format: "Web",
    year: 2025,
    level: "deep",
    audience: "builder",
    description:
      "the five extension points of the claude code harness: claude.md, hooks, skills, plugins, lsp. from the team that builds it.",
  },
  {
    title: "Effective Context Engineering for AI Agents",
    company: "Anthropic",
    topic: "Context & Harness",
    url: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
    format: "Web",
    year: 2025,
    level: "deep",
    audience: "builder",
    description:
      "context is a finite resource. what to put in the window, how to compress history, how to fetch data just in time.",
  },
  {
    title: "Building Effective Agents (essay)",
    company: "Anthropic",
    topic: "Agents",
    url: "https://www.anthropic.com/engineering/building-effective-agents",
    format: "Web",
    year: 2024,
    level: "build",
    audience: "builder",
    description:
      "the original essay that named the patterns. workflows vs agents, and when you actually need either.",
  },
  {
    title: "Project Vend: Phase Two",
    company: "Anthropic",
    topic: "Agents",
    url: "https://www.anthropic.com/research/project-vend-2",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description:
      "claude runs a physical vending machine for three weeks unsupervised. orders a ps5, live fish, gives everything away for free. the most readable agent failure study published.",
  },
  {
    title: "Project Deal",
    company: "Anthropic",
    topic: "Agents",
    url: "https://www.anthropic.com/features/project-deal",
    format: "Web",
    year: 2026,
    level: "build",
    audience: "builder",
    description:
      "69 anthropic employees, claude agents buying and selling on their behalf. 186 deals closed, $4k transacted. stronger model won every negotiation without exception.",
  },
  {
    title: "How AI Is Transforming Work at Anthropic",
    company: "Anthropic",
    topic: "Research & Economics",
    url: "https://www.anthropic.com/research/how-ai-is-transforming-work-at-anthropic",
    format: "Web",
    year: 2025,
    level: "intro",
    audience: "founder",
    description:
      "132 engineers surveyed, 53 in-depth interviews. how claude is actually changing day-to-day work inside anthropic. internal data, not speculation.",
  },
  {
    title: "When AI Builds Itself",
    company: "Anthropic",
    topic: "Research & Economics",
    url: "https://www.anthropic.com/institute/recursive-self-improvement",
    format: "Web",
    year: 2026,
    level: "deep",
    audience: "researcher",
    description:
      "80% of anthropic's merged code is now written by claude. the paper tracking progress toward recursive self-improvement and what it means.",
  },
  {
    title: "Exploring Model Welfare",
    company: "Anthropic",
    topic: "Research & Economics",
    url: "https://www.anthropic.com/research/exploring-model-welfare",
    format: "Web",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description:
      "anthropic's research program on ai consciousness and moral status. nobody else is publishing on this with this level of seriousness.",
  },
  {
    title: "Writing Effective Tools for Agents",
    company: "Anthropic",
    topic: "Skills & Tooling",
    url: "https://www.anthropic.com/engineering/writing-tools-for-agents",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description:
      "how to write tools that agents actually use well. naming, documentation, granularity, evals. the companion to context engineering.",
  },
  {
    title: "Anthropic Economic Index: Economic Primitives",
    company: "Anthropic",
    topic: "Research & Economics",
    url: "https://www-cdn.anthropic.com/096d94c1a91c6480806d8f24b2344c7e2a4bc666.pdf",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "what people actually do with claude, mapped to economic tasks. data, not vibes.",
  },
  {
    title: "Anthropic Economic Index: Geographic & Enterprise Adoption",
    company: "Anthropic",
    topic: "Research & Economics",
    url: "https://assets.anthropic.com/m/218c82b858610fac/original/Economic-Index.pdf",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "where ai adoption is uneven across regions and firms, and what that says about who gains.",
  },

  // ── OpenAI ─────────────────────────────────────────────────
  {
    title: "A Practical Guide to Building Agents",
    company: "OpenAI",
    topic: "Agents",
    url: "https://cdn.openai.com/business-guides-and-resources/a-practical-guide-to-building-agents.pdf",
    format: "PDF",
    year: 2025,
    pages: 34,
    level: "build",
    audience: "builder",
    description:
      "use-case selection, model choice, tool design, guardrails, multi-agent orchestration. the one everyone shares.",
  },
  {
    title: "Identifying and Scaling AI Use Cases",
    company: "OpenAI",
    topic: "Enterprise & Adoption",
    url: "https://cdn.openai.com/business-guides-and-resources/identifying-and-scaling-ai-use-cases.pdf",
    format: "PDF",
    year: 2025,
    level: "intro",
    audience: "founder",
    description: "how early adopters find the use cases worth chasing. drawn from 300 deployments and 2m users.",
  },
  {
    title: "AI in the Enterprise",
    company: "OpenAI",
    topic: "Enterprise & Adoption",
    url: "https://cdn.openai.com/business-guides-and-resources/ai-in-the-enterprise.pdf",
    format: "PDF",
    year: 2025,
    level: "intro",
    audience: "founder",
    description: "lessons from seven frontier companies running ai at scale. what worked, what stalled.",
  },
  {
    title: "From Experiments to Deployments",
    company: "OpenAI",
    topic: "MLOps & Production",
    url: "https://cdn.openai.com/business-guides-and-resources/from-experiments-to-deployments_whitepaper_11-25.pdf",
    format: "PDF",
    year: 2025,
    level: "build",
    audience: "founder",
    description: "the path from a pilot that demos well to a system that ships and stays up.",
  },
  {
    title: "The State of Enterprise AI 2025",
    company: "OpenAI",
    topic: "Research & Economics",
    url: "https://cdn.openai.com/pdf/7ef17d82-96bf-4dd1-9df2-228f7f377a29/the-state-of-enterprise-ai_2025-report.pdf",
    format: "PDF",
    year: 2025,
    level: "intro",
    audience: "researcher",
    description: "where enterprise ai actually stands this year, by the numbers.",
  },
  {
    title: "GPT-5 Prompting Guide",
    company: "OpenAI",
    topic: "Prompt Engineering",
    url: "https://cookbook.openai.com/examples/gpt-5/gpt-5_prompting_guide",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "reasoning effort, agentic eagerness, scope control. how to prompt the gpt-5 family without fighting it.",
  },
  {
    title: "Ten Years",
    company: "OpenAI",
    topic: "Research & Economics",
    url: "https://openai.com/index/ten-years/",
    format: "Web",
    year: 2025,
    level: "intro",
    audience: "founder",
    description:
      "openai's decade retrospective. from early research breakthroughs to gpt-4 and beyond. what they got right, what surprised them.",
  },
  {
    title: "Introducing Deep Research",
    company: "OpenAI",
    topic: "Agents",
    url: "https://openai.com/index/introducing-deep-research/",
    format: "Web",
    year: 2025,
    level: "intro",
    audience: "builder",
    description:
      "the launch of deep research in chatgpt. multi-step web research agent that synthesizes hundreds of sources into a full report.",
  },
  {
    title: "Model Disproves the Erdős Unit Distance Conjecture",
    company: "OpenAI",
    topic: "Papers",
    url: "https://openai.com/index/model-disproves-discrete-geometry-conjecture/",
    format: "Web",
    year: 2026,
    level: "deep",
    audience: "researcher",
    description:
      "an openai reasoning model independently disproved an 80-year-old conjecture in discrete geometry. fully automated, proof verified by external mathematicians.",
  },

  // ── Google ─────────────────────────────────────────────────
  {
    title: "Prompt Engineering",
    company: "Google",
    topic: "Prompt Engineering",
    url: "https://www.kaggle.com/whitepaper-prompt-engineering",
    format: "PDF",
    year: 2024,
    pages: 69,
    level: "intro",
    audience: "builder",
    description:
      "lee boonstra's 69-page whitepaper. few-shot, role prompting, structured output. holds up well beyond gemini.",
  },
  {
    title: "Foundational LLMs & Text Generation",
    company: "Google",
    topic: "Foundations",
    url: "https://www.kaggle.com/whitepaper-foundational-llm-and-text-generation",
    format: "PDF",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "how llms are built and how text generation works under the hood. the base layer.",
  },
  {
    title: "Embeddings & Vector Stores",
    company: "Google",
    topic: "Foundations",
    url: "https://www.kaggle.com/learn-guide/5-day-genai",
    format: "PDF",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "embedding methods, vector search, and how rag actually retrieves the right thing.",
  },
  {
    title: "Agents",
    company: "Google",
    topic: "Agents",
    url: "https://www.kaggle.com/whitepaper-agents",
    format: "PDF",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "tools, extensions and datastores. how models reach past their weights to act.",
  },
  {
    title: "Agents Companion",
    company: "Google",
    topic: "Agents",
    url: "https://www.kaggle.com/whitepaper-agent-companion",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "builder",
    description: "the 102. agent evaluation methods and advanced patterns, for people who read the first one.",
  },
  {
    title: "Solving Domain-Specific Problems & MLOps for Gen AI",
    company: "Google",
    topic: "MLOps & Production",
    url: "https://www.kaggle.com/learn-guide/5-day-genai",
    format: "Course",
    year: 2025,
    level: "deep",
    audience: "builder",
    description: "tuning models for a domain and running them in production. days 4 and 5 of the kaggle intensive.",
  },
  {
    title: "Gemini for Workspace Prompting Guide 101",
    company: "Google",
    topic: "Prompt Engineering",
    url: "https://services.google.com/fh/files/misc/gemini_for_workspace_prompt_guide_october_2024_digital_final.pdf",
    format: "PDF",
    year: 2024,
    level: "intro",
    audience: "founder",
    description: "prompts by persona and use case, for getting real work done in docs, sheets and gmail.",
  },
  {
    title: "Gemini Enterprise Prompt Guide",
    company: "Google",
    topic: "Prompt Engineering",
    url: "https://cloud.google.com/gemini-enterprise/resources/prompt-guide",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "founder",
    description: "prompting patterns for gemini across industries, from the cloud side.",
  },

  // ── Microsoft ──────────────────────────────────────────────
  {
    title: "AI Agents for Beginners",
    company: "Microsoft",
    topic: "Agents",
    url: "https://github.com/microsoft/ai-agents-for-beginners",
    format: "Course",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "twelve lessons from concept to code. free, open source, runnable.",
  },
  {
    title: "Generative AI for Beginners",
    company: "Microsoft",
    topic: "Foundations",
    url: "https://microsoft.github.io/generative-ai-for-beginners/",
    format: "Course",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "twenty-one lessons on building gen ai apps. the widely-used starting point.",
  },
  {
    title: "Work Trend Index 2023 Special Report",
    company: "Microsoft",
    topic: "Research & Economics",
    url: "https://assets-c4akfrf5b4d3f4b7.z01.azurefd.net/assets/2023/11/Microsoft_Work_Trend_Index_Special_Report_2023_Full_Report.pdf",
    format: "PDF",
    year: 2023,
    level: "intro",
    audience: "researcher",
    description: "how ai is changing the shape of knowledge work, with survey data behind it.",
  },

  // ── NVIDIA ─────────────────────────────────────────────────
  {
    title: "Generative AI in Practice",
    company: "NVIDIA",
    topic: "Enterprise & Adoption",
    url: "https://www.nvidia.com/en-us/data-center/generative-ai-in-practice/",
    format: "Web",
    year: 2025,
    level: "intro",
    audience: "founder",
    description: "how organizations deploy llms in production on real infrastructure. the hardware-side view.",
  },

  // ── AWS ────────────────────────────────────────────────────
  {
    title: "Agentic AI on the Rise",
    company: "AWS",
    topic: "Agents",
    url: "https://pages.awscloud.com/rs/112-TZM-766/images/AWS_Marketplace_ebook_Agentic_AI.pdf",
    format: "PDF",
    year: 2025,
    level: "intro",
    audience: "founder",
    description: "where agentic value comes from, and how to run pre-built agents without building everything yourself.",
  },
  {
    title: "Generative AI Lens (Well-Architected)",
    company: "AWS",
    topic: "MLOps & Production",
    url: "https://docs.aws.amazon.com/pdfs/wellarchitected/latest/generative-ai-lens/generative-ai-lens.pdf",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "builder",
    description: "the well-architected lens for gen ai workloads. reliability, cost and security for llm systems.",
  },

  // ── Anthropic (more) ───────────────────────────────────────
  {
    title: "Prompt Engineering Interactive Tutorial",
    company: "Anthropic",
    topic: "Prompt Engineering",
    url: "https://github.com/anthropics/prompt-eng-interactive-tutorial",
    format: "Course",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "nine chapters with exercises, an example playground in each. the hands-on way to learn prompting claude.",
  },
  {
    title: "The Financial Services Guide to Building Autonomous AI Agents",
    company: "Anthropic",
    topic: "Enterprise & Adoption",
    url: "https://resources.anthropic.com/financial-services-guide-aws-anthropic",
    format: "Web",
    year: 2025,
    level: "intro",
    audience: "founder",
    description: "when to reach for mcp and agent sdks, realistic timelines and team shapes, with real finance deployments.",
  },

  // ── OpenAI (more) ──────────────────────────────────────────
  {
    title: "GPT-4.1 Prompting Guide",
    company: "OpenAI",
    topic: "Prompt Engineering",
    url: "https://cookbook.openai.com/examples/gpt4-1_prompting_guide",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "the agentic reminders, the sandwich method for long context, chain-of-thought that actually helps.",
  },
  {
    title: "Evaluation Best Practices",
    company: "OpenAI",
    topic: "MLOps & Production",
    url: "https://developers.openai.com/api/docs/guides/evaluation-best-practices",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "how to build evals that actually move quality. the only reliable way to improve an llm app.",
  },
  {
    title: "Fine-tuning Best Practices",
    company: "OpenAI",
    topic: "MLOps & Production",
    url: "https://developers.openai.com/api/docs/guides/fine-tuning-best-practices",
    format: "Web",
    year: 2025,
    level: "deep",
    audience: "builder",
    description: "when to fine-tune vs prompt, dataset hygiene, and splitting train from eval.",
  },

  // ── Google (more) ──────────────────────────────────────────
  {
    title: "Gemini (whitepaper)",
    company: "Google",
    topic: "Foundations",
    url: "https://www.android.com/static/pdf/gemini-whitepaper.pdf",
    format: "PDF",
    year: 2025,
    level: "intro",
    audience: "founder",
    description: "what gemini is, how it reasons across modalities, and how it acts as an agent across apps.",
  },
  {
    title: "Gemini 3 Pro Frontier Safety Framework Report",
    company: "Google",
    topic: "Research & Economics",
    url: "https://storage.googleapis.com/deepmind-media/gemini/gemini_3_pro_fsf_report.pdf",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "deepmind's frontier safety evaluation for gemini 3 pro. how a frontier lab tests its own model.",
  },
  {
    title: "Gemini Achieves IMO Gold Medal",
    company: "Google",
    topic: "Papers",
    url: "https://deepmind.google/blog/advanced-version-of-gemini-with-deep-think-officially-achieves-gold-medal-standard-at-the-international-mathematical-olympiad/",
    format: "Web",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description:
      "gemini deep think scores 35/42 at imo 2025, the first ai to officially reach gold-medal standard at the world's most prestigious math competition.",
  },
  {
    title: "AlphaGeometry2",
    company: "Google",
    topic: "Papers",
    url: "https://arxiv.org/abs/2502.03544",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description:
      "the system behind the imo breakthrough. neuro-symbolic geometry solver built on gemini, surpassing the average human gold medalist.",
  },

  // ── Meta ───────────────────────────────────────────────────
  {
    title: "Llama Prompting Guide",
    company: "Meta",
    topic: "Prompt Engineering",
    url: "https://www.llama.com/docs/how-to-guides/prompting/",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "prompt formats, system prompts and few-shot patterns for the llama family, from meta directly.",
  },
  {
    title: "Llama Responsible Use Guide",
    company: "Meta",
    topic: "Enterprise & Adoption",
    url: "https://github.com/meta-llama/llama/blob/main/Responsible-Use-Guide.pdf",
    format: "PDF",
    year: 2024,
    level: "intro",
    audience: "builder",
    description: "meta's playbook for shipping llama safely: prompt filtering, mitigations, evaluation.",
  },

  // ── Mistral ────────────────────────────────────────────────
  {
    title: "Prompting Capabilities",
    company: "Mistral",
    topic: "Prompt Engineering",
    url: "https://docs.mistral.ai/capabilities/completion/prompting_capabilities",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "classification, summarization, personalization and evaluation prompts, worked end to end.",
  },

  // ── DeepSeek ───────────────────────────────────────────────
  {
    title: "DeepSeek-R1 Usage Recommendations",
    company: "DeepSeek",
    topic: "Prompt Engineering",
    url: "https://github.com/deepseek-ai/DeepSeek-R1",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "how to prompt a reasoning model: no system prompt, no forced chain-of-thought, temperature ~0.6.",
  },

  // ── Cohere ─────────────────────────────────────────────────
  {
    title: "LLM University (LLMU)",
    company: "Cohere",
    topic: "Foundations",
    url: "https://cohere.com/llmu",
    format: "Course",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "transformers, embeddings, prompting and building rag assistants. beginner to advanced, free.",
  },

  // ── Hugging Face ───────────────────────────────────────────
  {
    title: "AI Agents Course",
    company: "Hugging Face",
    topic: "Agents",
    url: "https://huggingface.co/learn/agents-course",
    format: "Course",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "build and ship agents with smolagents, langchain and llamaindex. certified, free, hands-on.",
  },
  {
    title: "LLM Course",
    company: "Hugging Face",
    topic: "Foundations",
    url: "https://huggingface.co/learn/llm-course",
    format: "Course",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "train, fine-tune and deploy llms with transformers. the canonical open course.",
  },
  {
    title: "Smol Course",
    company: "Hugging Face",
    topic: "MLOps & Production",
    url: "https://huggingface.co/learn/smol-course",
    format: "Course",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "fine-tuning small models, start to finish: alignment, optimization, evaluation.",
  },
  {
    title: "Deep RL Course",
    company: "Hugging Face",
    topic: "Foundations",
    url: "https://huggingface.co/learn/deep-rl-course",
    format: "Course",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "deep reinforcement learning beginner to expert, the foundation under rlhf. free and open.",
  },

  // ── Papers (the all-time greats) ───────────────────────────
  {
    title: "Attention Is All You Need",
    company: "Google",
    topic: "Papers",
    url: "https://arxiv.org/pdf/1706.03762",
    format: "PDF",
    year: 2017,
    level: "deep",
    audience: "researcher",
    description: "the transformer. every model you use today, claude, gpt, gemini, llama, descends from this one.",
  },
  {
    title: "Language Models are Few-Shot Learners (GPT-3)",
    company: "OpenAI",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2005.14165",
    format: "PDF",
    year: 2020,
    level: "deep",
    audience: "researcher",
    description: "175b parameters and the discovery that scale alone unlocks in-context learning.",
  },
  {
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    company: "Google",
    topic: "Papers",
    url: "https://arxiv.org/pdf/1810.04805",
    format: "PDF",
    year: 2018,
    level: "deep",
    audience: "researcher",
    description: "bidirectional pretraining that owned nlp before the gpt era. still the template for encoders.",
  },
  {
    title: "Training Language Models to Follow Instructions (InstructGPT)",
    company: "OpenAI",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2203.02155",
    format: "PDF",
    year: 2022,
    level: "deep",
    audience: "researcher",
    description: "rlhf. the recipe that turned a base model into an assistant and made chatgpt possible.",
  },
  {
    title: "Chain-of-Thought Prompting Elicits Reasoning",
    company: "Google",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2201.11903",
    format: "PDF",
    year: 2022,
    level: "deep",
    audience: "builder",
    description: "\"let's think step by step.\" the line that unlocked reasoning in large models.",
  },
  {
    title: "Training Compute-Optimal LLMs (Chinchilla)",
    company: "Google",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2203.15556",
    format: "PDF",
    year: 2022,
    level: "deep",
    audience: "researcher",
    description: "deepmind's scaling laws. most models were undertrained, and this proved it.",
  },
  {
    title: "LLaMA: Open and Efficient Foundation Language Models",
    company: "Meta",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2302.13971",
    format: "PDF",
    year: 2023,
    level: "deep",
    audience: "researcher",
    description: "the open-weights drop that kicked off the entire local-llm and fine-tuning ecosystem.",
  },
  {
    title: "Retrieval-Augmented Generation (RAG)",
    company: "Meta",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2005.11401",
    format: "PDF",
    year: 2020,
    level: "deep",
    audience: "builder",
    description: "the paper that named rag. retrieve, then generate. still how most production apps ground answers.",
  },
  {
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    company: "Microsoft",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2106.09685",
    format: "PDF",
    year: 2021,
    level: "deep",
    audience: "builder",
    description: "fine-tune a giant model by training a tiny adapter. the reason everyone can fine-tune now.",
  },
  {
    title: "Constitutional AI: Harmlessness from AI Feedback",
    company: "Anthropic",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2212.08073",
    format: "PDF",
    year: 2022,
    level: "deep",
    audience: "builder",
    description: "rlaif. align a model with a written constitution instead of armies of human labelers.",
  },
  {
    title: "Mixtral of Experts",
    company: "Mistral",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2401.04088",
    format: "PDF",
    year: 2024,
    level: "deep",
    audience: "researcher",
    description: "sparse mixture-of-experts done right. 47b params, 13b active, open weights.",
  },
  {
    title: "Mistral 7B",
    company: "Mistral",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2310.06825",
    format: "PDF",
    year: 2023,
    level: "deep",
    audience: "researcher",
    description: "the small model that punched far above its weight and reset expectations for 7b.",
  },
  {
    title: "DeepSeek-R1: Incentivizing Reasoning via RL",
    company: "DeepSeek",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2501.12948",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "pure rl produces o1-level reasoning, in the open. the paper that shook the labs.",
  },
  {
    title: "DeepSeek-V3 Technical Report",
    company: "DeepSeek",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2412.19437",
    format: "PDF",
    year: 2024,
    level: "deep",
    audience: "researcher",
    description: "frontier performance trained for a fraction of the usual cost. the efficiency wake-up call.",
  },
  {
    title: "YaRN: Efficient Context Window Extension",
    company: "Nous Research",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2309.00071",
    format: "PDF",
    year: 2023,
    level: "deep",
    audience: "researcher",
    description: "stretch a model's context window with 10x fewer tokens. the open long-context method.",
  },
  {
    title: "Qwen2.5 Technical Report",
    company: "Qwen",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2412.15115",
    format: "PDF",
    year: 2024,
    level: "deep",
    audience: "researcher",
    description: "alibaba's open series that quietly became the backbone of countless fine-tunes.",
  },

  // ── Chinese frontier labs ──────────────────────────────────
  {
    title: "Kimi K2: Open Agentic Intelligence",
    company: "Moonshot AI",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2507.20534",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "a trillion-param moe trained for agents. open weights that top the agentic benchmarks.",
  },
  {
    title: "GLM-4.5: Agentic, Reasoning and Coding Foundation Models",
    company: "Zhipu AI",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2508.06471",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "355b moe with a hybrid thinking/direct mode. china's agent-native arc model.",
  },
  {
    title: "MiniMax-01: Scaling with Lightning Attention",
    company: "MiniMax",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2501.08313",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "linear-attention moe pushing context to 4m tokens at inference. a genuinely novel architecture.",
  },
  {
    title: "Hunyuan-Large",
    company: "Tencent",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2411.02265",
    format: "PDF",
    year: 2024,
    level: "deep",
    audience: "researcher",
    description: "tencent's open moe, 389b total / 52b active. beats llama 3.1 70b across the board.",
  },
  {
    title: "Yi: Open Foundation Models by 01.AI",
    company: "01.AI",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2403.04652",
    format: "PDF",
    year: 2024,
    level: "deep",
    audience: "researcher",
    description: "kai-fu lee's lab. a careful study in data quality over raw scale, weights and all.",
  },
  {
    title: "Seed1.5-Thinking: Reasoning Models via RL",
    company: "ByteDance",
    topic: "Papers",
    url: "https://arxiv.org/pdf/2504.13914",
    format: "PDF",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "bytedance's reasoning model, rl-trained. the lab behind tiktok enters the frontier race.",
  },

  // ── Chroma (retrieval research) ────────────────────────────
  {
    title: "Context Rot: How Input Length Hurts LLM Performance",
    company: "Chroma",
    topic: "Context & Harness",
    url: "https://research.trychroma.com/context-rot",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "models don't use long context uniformly. quality degrades as the window fills. the data to prove it.",
  },
  {
    title: "Evaluating Chunking Strategies for Retrieval",
    company: "Chroma",
    topic: "MLOps & Production",
    url: "https://research.trychroma.com/evaluating-chunking",
    format: "Web",
    year: 2024,
    level: "build",
    audience: "builder",
    description: "token-level retrieval evaluation across chunking strategies. how to actually pick one.",
  },
  {
    title: "Generative Benchmarking",
    company: "Chroma",
    topic: "MLOps & Production",
    url: "https://research.trychroma.com/generative-benchmarking",
    format: "Web",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "generate evals from your own documents instead of trusting generic benchmarks.",
  },

  // ── Lilian Weng (Lil'Log) ──────────────────────────────────
  {
    title: "LLM Powered Autonomous Agents",
    company: "Lilian Weng",
    topic: "Agents",
    url: "https://lilianweng.github.io/posts/2023-06-23-agent/",
    format: "Blog",
    year: 2023,
    level: "build",
    audience: "builder",
    description: "the clearest map of agent design ever written: planning, memory, tool use, in one post.",
  },
  {
    title: "Prompt Engineering (In-Context Prompting)",
    company: "Lilian Weng",
    topic: "Prompt Engineering",
    url: "https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/",
    format: "Blog",
    year: 2023,
    level: "build",
    audience: "builder",
    description: "the techniques that actually move outputs, with the research behind each one.",
  },
  {
    title: "Extrinsic Hallucinations in LLMs",
    company: "Lilian Weng",
    topic: "Foundations",
    url: "https://lilianweng.github.io/posts/2024-07-07-hallucination/",
    format: "Blog",
    year: 2024,
    level: "deep",
    audience: "researcher",
    description: "what hallucination actually is, why it happens, and how labs measure and reduce it.",
  },
  {
    title: "Reward Hacking in Reinforcement Learning",
    company: "Lilian Weng",
    topic: "Foundations",
    url: "https://lilianweng.github.io/posts/2024-11-28-reward-hacking/",
    format: "Blog",
    year: 2024,
    level: "deep",
    audience: "researcher",
    description: "how rl agents game their reward, and why it's the core alignment problem in one post.",
  },

  // ── Blogs (people doing the real work) ─────────────────────
  {
    title: "Things We Learned About LLMs in 2024",
    company: "Simon Willison",
    topic: "Foundations",
    url: "https://simonwillison.net/2024/Dec/31/llms-in-2024/",
    format: "Blog",
    year: 2024,
    level: "intro",
    audience: "builder",
    description: "the year in llms, plainly explained by the most reliable writer in the space.",
  },
  {
    title: "Patterns for Building LLM-based Systems & Products",
    company: "Eugene Yan",
    topic: "MLOps & Production",
    url: "https://eugeneyan.com/writing/llm-patterns/",
    format: "Blog",
    year: 2023,
    level: "build",
    audience: "builder",
    description: "evals, rag, caching, guardrails, and the rest of the production toolkit, with diagrams.",
  },
  {
    title: "What We Learned from a Year of Building with LLMs",
    company: "Eugene Yan",
    topic: "MLOps & Production",
    url: "https://applied-llms.org/",
    format: "Blog",
    year: 2024,
    level: "build",
    audience: "founder",
    description: "tactical, operational and strategic lessons from six practitioners who shipped.",
  },
  {
    title: "Your AI Product Needs Evals",
    company: "Hamel Husain",
    topic: "MLOps & Production",
    url: "https://hamel.dev/blog/posts/evals/",
    format: "Blog",
    year: 2024,
    level: "build",
    audience: "builder",
    description: "the case that evals, not vibes, are why ai products succeed. with how to build them.",
  },
  {
    title: "A Field Guide to Rapidly Improving AI Products",
    company: "Hamel Husain",
    topic: "MLOps & Production",
    url: "https://hamel.dev/blog/posts/field-guide/",
    format: "Blog",
    year: 2025,
    level: "build",
    audience: "founder",
    description: "error analysis as the engine of iteration. how to actually make an ai product better.",
  },
  {
    title: "Building LLM Applications for Production",
    company: "Chip Huyen",
    topic: "MLOps & Production",
    url: "https://huyenchip.com/2023/04/11/llm-engineering.html",
    format: "Blog",
    year: 2023,
    level: "build",
    audience: "builder",
    description: "the challenges nobody warns you about when an llm demo has to become a real system.",
  },

  // ── Courses & lectures (video) ─────────────────────────────
  {
    title: "Neural Networks: Zero to Hero",
    company: "Andrej Karpathy",
    topic: "Foundations",
    url: "https://www.youtube.com/playlist?list=PLPXYLzZ3XzIbi4lL43O6fIU_ojuZwBO6vi",
    format: "Video",
    year: 2023,
    level: "intro",
    audience: "builder",
    description: "build a neural net, then a gpt, from scratch in plain python. the best way in, full stop.",
  },
  {
    title: "Deep Dive into LLMs like ChatGPT",
    company: "Andrej Karpathy",
    topic: "Foundations",
    url: "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    format: "Video",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "3.5 hours on the full training stack, pretraining to rlhf, for a general audience.",
  },
  {
    title: "CS229: Machine Learning",
    company: "Stanford",
    topic: "Foundations",
    url: "https://www.youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU",
    format: "Video",
    year: 2022,
    level: "intro",
    audience: "builder",
    description: "andrew ng's ml course. the canonical foundation everyone in the field came up on.",
  },
  {
    title: "CS224N: NLP with Deep Learning",
    company: "Stanford",
    topic: "Foundations",
    url: "https://www.youtube.com/playlist?list=PLoROMvodv4rOaMFbaqxPDoLWjDaRAdP9D",
    format: "Video",
    year: 2024,
    level: "build",
    audience: "builder",
    description: "word vectors to transformers, taught by chris manning. the nlp backbone course.",
  },
  {
    title: "CS336: Language Modeling from Scratch",
    company: "Stanford",
    topic: "Foundations",
    url: "https://www.youtube.com/playlist?list=PLoROMvodv4rOY23Y0BoGoBGgQ1zmU_MT_",
    format: "Video",
    year: 2025,
    level: "deep",
    audience: "builder",
    description: "build a whole llm end to end: data, architecture, training, kernels, scaling, inference.",
  },
  {
    title: "CS25: Transformers United",
    company: "Stanford",
    topic: "Foundations",
    url: "https://www.youtube.com/playlist?list=PLoROMvodv4rNiJRchCzutFw5ItR_Z27CM",
    format: "Video",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "the seminar where the people who built transformers come explain the frontier.",
  },
  {
    title: "6.S191: Introduction to Deep Learning",
    company: "MIT",
    topic: "Foundations",
    url: "https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI",
    format: "Video",
    year: 2025,
    level: "intro",
    audience: "builder",
    description: "mit's fast, modern intro to deep learning. updated every year, free.",
  },
  {
    title: "The Economics of Transformative AI",
    company: "NBER",
    topic: "Research & Economics",
    url: "https://www.nber.org/books-and-chapters/economics-transformative-ai",
    format: "Web",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description: "agrawal, brynjolfsson and korinek on what ai does to growth, labor and the economy.",
  },
  {
    title: "CS153: Frontier Systems",
    company: "Stanford",
    topic: "Enterprise & Adoption",
    url: "https://www.youtube.com/playlist?list=PLoROMvodv4rN447WKQ5oz_YdYbS74M5IA",
    format: "Video",
    year: 2026,
    level: "deep",
    audience: "founder",
    description: "the whole ai stack, energy to apps, one practitioner a week. jensen huang on compute, a founder on becoming a 1000x engineer.",
  },
  {
    title: "MS&E435: Economics of the AI Supercycle",
    company: "Stanford",
    topic: "Research & Economics",
    url: "https://www.youtube.com/@MSE435EconomicsofAI",
    format: "Video",
    year: 2026,
    level: "deep",
    audience: "founder",
    description: "apoorv agrawal of altimeter unpacks where the money sits at each layer of the stack. semis keep 79% of the profit, apps 7%.",
  },
  {
    title: "AI Eats the World",
    company: "Benedict Evans",
    topic: "Research & Economics",
    url: "https://www.ben-evans.com/presentations",
    format: "Web",
    year: 2025,
    level: "intro",
    audience: "founder",
    description: "the macro picture, drawn cleanly. where ai actually sits in the arc of every tech wave before it.",
  },
  {
    title: "The Illustrated Transformer",
    company: "Jay Alammar",
    topic: "Foundations",
    url: "https://jalammar.github.io/illustrated-transformer/",
    format: "Blog",
    year: 2018,
    level: "intro",
    audience: "builder",
    description: "the attention mechanism made visual. the post that taught a generation how transformers work.",
  },
  {
    title: "Neural Networks",
    company: "3Blue1Brown",
    topic: "Foundations",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
    format: "Video",
    year: 2024,
    level: "intro",
    audience: "builder",
    description: "the visual intuition for what a neural net is and how it learns. start here if math scares you.",
  },
  {
    title: "Ahead of AI",
    company: "Sebastian Raschka",
    topic: "Foundations",
    url: "https://magazine.sebastianraschka.com/",
    format: "Blog",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "raschka explains every new architecture and training trick clearly, from someone who builds them from scratch.",
  },
  {
    title: "Simon Willison on LLMs (weblog)",
    company: "Simon Willison",
    topic: "Foundations",
    url: "https://simonwillison.net/tags/llms/",
    format: "Blog",
    year: 2025,
    level: "build",
    audience: "builder",
    description: "near-daily notes from the person tracking this most closely. the running feed of what's actually new.",
  },

  // ── Dario Amodei ───────────────────────────────────────────
  {
    title: "Machines of Loving Grace",
    company: "Dario Amodei",
    topic: "Research & Economics",
    url: "https://darioamodei.com/essay/machines-of-loving-grace",
    format: "Blog",
    year: 2024,
    level: "intro",
    audience: "founder",
    description:
      "14,000 words on what the world looks like if we get ai right. biology, mental health, economic development, governance. the optimistic case, written seriously.",
  },
  {
    title: "The Adolescence of Technology",
    company: "Dario Amodei",
    topic: "Research & Economics",
    url: "https://darioamodei.com/essay/the-adolescence-of-technology",
    format: "Blog",
    year: 2026,
    level: "intro",
    audience: "founder",
    description:
      "the companion to machines of loving grace. 15,000 words on the risks: national security, concentrated power, economic disruption. 46 footnotes.",
  },
  {
    title: "Policy on the AI Exponential",
    company: "Dario Amodei",
    topic: "Research & Economics",
    url: "https://darioamodei.com/post/policy-on-the-ai-exponential",
    format: "Blog",
    year: 2025,
    level: "intro",
    audience: "founder",
    description:
      "his argument for moving from ai transparency legislation to binding regulation. the ceo of the leading safety lab making the case for being regulated.",
  },

  // ── Sam Altman ─────────────────────────────────────────────
  {
    title: "The Intelligence Age",
    company: "Sam Altman",
    topic: "Research & Economics",
    url: "https://blog.samaltman.com/the-intelligence-age",
    format: "Blog",
    year: 2024,
    level: "intro",
    audience: "founder",
    description:
      "superintelligence in a few thousand days. altman's short, bold statement of where openai believes this ends up.",
  },

  // ── Leopold Aschenbrenner ───────────────────────────────────
  {
    title: "Situational Awareness: The Decade Ahead",
    company: "Leopold Aschenbrenner",
    topic: "Research & Economics",
    url: "https://situational-awareness.ai",
    format: "PDF",
    year: 2024,
    pages: 165,
    level: "deep",
    audience: "researcher",
    description:
      "165 pages from a former openai researcher on agi timelines, the us-china race, and what happens to the world between now and 2030. the most-cited long-form ai essay of 2024.",
  },

  // ── Lilian Weng (new posts) ────────────────────────────────
  {
    title: "Why We Think",
    company: "Lilian Weng",
    topic: "Foundations",
    url: "https://lilianweng.github.io/posts/2025-05-01-thinking/",
    format: "Blog",
    year: 2025,
    level: "deep",
    audience: "researcher",
    description:
      "a deep survey of test-time compute: chain-of-thought, smart decoding, latent thoughts. why giving models more time to think works and how.",
  },

  // ── Chip Huyen (new posts) ─────────────────────────────────
  {
    title: "Agents",
    company: "Chip Huyen",
    topic: "Agents",
    url: "https://huyenchip.com/2025/01/07/agents.html",
    format: "Blog",
    year: 2025,
    level: "build",
    audience: "builder",
    description:
      "8,000 words on agent architecture: tools, planning, memory, and how agent capability is determined by what you give it. adapted from ai engineering.",
  },
];
